// <auto-generated />
using Basic.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Basic.Migrations
{
    [DbContext(typeof(LoggerContext))]
    [Migration("20180403024754_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Basic.Model.LogModel", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId");

                    b.Property<string>("ExceptionType");

                    b.Property<DateTime>("LogTime");

                    b.Property<string>("LogType");

                    b.Property<string>("Message")
                        .IsUnicode(true);

                    b.Property<string>("StackTrace");

                    b.HasKey("LogId");

                    b.ToTable("LogModel");
                });
#pragma warning restore 612, 618
        }
    }
}
